version: '3'
services:
  rever-poxy:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  service:
    image: vad1mo/hello-world-rest
    container_name: service
    ports:
      - "5000:5050"

  service2:
    image: chentex/go-rest-api
    container_name: service2
    ports:
      - "5001:8080"

  